# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    helper:
        class: AppBundle\Helper\Helper
        arguments: [@doctrine]
    market:
        class: AppBundle\Helper\Market
        arguments: ['@doctrine', '@helper']
    parser:
        class: AppBundle\Helper\Parser
        arguments: ['@doctrine', '@helper']
    authentication_handler:
        class: AppBundle\Helper\AuthenticationHandler
        calls:
            - [ setContainer, [ @service_container ] ]
    cache:
        class: AppBundle\Helper\Cache
        arguments: ['@doctrine', '@helper', '@market']
    lineItemComparator:
        class: AppBundle\Helper\LineItemComparator
        arguments: ['@market']

    eve_sso_authenticator:
            class: AppBundle\Security\EveSSOAuthenticator
            arguments: ['@doctrine.orm.entity_manager', '@router', '%sso_client_id%', '%sso_secret_key%']

    role_manager:
            class: AppBundle\Security\RoleManager
            arguments: ['@doctrine.orm.entity_manager']
